### ISSUE TITLE
Question: Have you encountered the `Website Unaccessible` error?

### ISSUE THREAD

**Issue by jshleeb** [hermannsblum/kindle_infoscreen#45]
Hello, thanks for sharing your project! There isn't an issue with your repo, I'm just opening this as a way to communicate.

I'm building my own kindle infoscreen webapp for the transit service in my area. When I initially access it with the kindle browser, it works and polls every minute. But after about 20min to < 2 hours of leaving the page open in the kindle browser, this error message pops up: `Website Unaccessible. Sorry, the browser cannot access this website.`. It doesn't seem to me like there would be a reason for memory usage to increase/be an issue.

I'm wondering if you've encountered this error message before? Would you have an idea what it means, or how to work around it? Or if you have any tips on how to develop for and debug the kindle browser?

Thanks!

**Comment by hermannsblum** [comment]
Happy to help! How are you trying to access the website? The mode I usually use is to actually access the html file on the kindle through the browser, and there I never had an issue. I also once tried a webserver on local network over http and that worked, but it may be that some updates to the kindle browser make this more difficult.

**Comment by jshleeb** [comment]
Thank you! Huh, that's interesting. I started out as you suggest, opening the file at `file:///mnt/us/documents/test.html`, then trying at `file:///mnt/us/test.html`. Those both eventually led to the `Website Unaccessible` error on a kindle `5.12.2.2`, so I tried hosting the website on github pages, and that still caused the error on two different kindles running `5.12.2.2` and `5.16.6`.

Have you ever seen that error before? I wish I could see console logs 😅

**Comment by hermannsblum** [comment]
yes, not seeing the logs is the most annoying part, it leaves you with just trial & error...

I just checked, my kindle recently updated to 5.14.3.0.1 and it still works with the filepath. I have never seen this error before, at least not that I remember. Sorry

**Comment by jshleeb** [comment]
No worries, thanks for helping out a random person opening an "issue"! I think I'll try maybe a network-less long-running clock app, or hitting a different service's API, and see if I still get the error. Thanks!
