### ISSUE TITLE
Invalid Protocol

### ISSUE THREAD

**Issue by drgnomage** [hermannsblum/kindle_infoscreen#8]
While trying to access the file://// URL the browser returns:

Invalid Protocol

Web Browser cannot download files using this protocol.  Only HTTP and HTTPS protocols are supported.

I'm assuming this might be because I'm using and 1st Gen Kindle Paperwhite?

**Comment by drgnomage** [comment]
Looks like an update broke the ability to use the file:// protocol entirely.  Good old amazon, removing peoples ability to use their hardware.

**Comment by hermannsblum** [comment]
Yes, according to [this thread](https://www.mobileread.com/forums/showthread.php?t=24127) unfortunately the file URL does not work on kindle1...
However, maybe a workaround for you could be to use homeassistant as a web server, see [this reddit comment](https://reddit.com/r/homeassistant/comments/hd4n9k/_/fvkipo1/?context=1) that brought up that idea. Be aware however that this exposes the access token to the network.

**Comment by hermannsblum** [comment]
@drgnomage Uups, there is actually a typo in the readme. On my paperwhite 3 which should have latest firmware it works with `file:///mnt/us/documents/index.html` (one `/` less than in the README)

**Comment by drgnomage** [comment]
Aha, that seems to be working!

 I also misunderstood which index.html to deploy, I put the index.html from the root of the repo and the dist folder onto the Kindle!  I would update the readme to say something along the lines of:

> Put the contents of dist/ into the documents folder on the Kindle.

However, I much prefer it on the Home Assistant web server itself.  As that is backed up a little more often than my Kindle.
